services:
  midscene-pc:
    image: midpc
    container_name: midpc
    devices:
      - /dev/fuse:/dev/fuse
    ports:
      - "4000:4000"
      # - "5000:5000"
      # - "10022:22"
      - "3767:3767"
      - "3768:3768"
      - "9223:9223"
    env_file: .env
    privileged: true
    shm_size: 4g
    volumes:
      - /onas/share1:/onas/share3
      - /onas/share2:/onas/share3
      - /onas/share3:/onas/share3
      - /mnt/s3:/s3
      - ./data/Downloads:/home/ubuntu/Downloads
    cgroup: host
    restart: unless-stopped
    tty: true
